# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_control_controller

  arm_control_controller:
    type: FollowJointTrajectory
    joints:
      - joint0
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5